using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace VolunteerManagementSystem.Models
{
    public class FakeVolunteerRepository : IVolunteerRepository
    {
        public IEnumerable<Volunteer> Volunteers => new List<Volunteer> {new Volunteer { VolunteerID =  0, FirstName =  "Matthew", LastName =  "Campbell", Username =  "CampbellSoup", Password =  "IDontHaveTimeForPasswords", CentersPreferred =  "Outdoors", SkillsInterests =  "Survival", Availability =  "TRF", Address =  "9312 West Avondale Drive", PhoneNumber =  "8392951859", Email =  "abert@hotmail.com", Education =  "Adventure Education", Licenses =  "None", EmergencyName =  "Bob Campbell", EmergencyPhone =  "3892918042", EmergencyEmail =  "afjeioqw@gmail.com", EmergencyAddress =  "708 Worcester Drive", ValidLicense =  false, ValidSocial =  false, Approval  =  "Inactive" },
new Volunteer { VolunteerID =  1, FirstName =  "Al", LastName =  "Jebra", Username =  "algebrarox", Password =  "mathisawesome", CentersPreferred =  "Main Office", SkillsInterests =  "Math/Accounting", Availability =  "MTWRF", Address =  "94 Ridgefield", PhoneNumber =  "9301859310", Email =  "math@gmail.com", Education =  "Accounting", Licenses =  "None", EmergencyName =  "Cal Culus", EmergencyPhone =  "9282109094", EmergencyEmail =  "maths@gmail.com", EmergencyAddress =  "6174 Kaprekar Boulevard", ValidLicense =  false, ValidSocial =  false, Approval  =  "Pending Approval" },
new Volunteer { VolunteerID =  2, FirstName =  "Hugh", LastName =  "Jissue", Username =  "Ihaveaproblem", Password =  "noproblemsinthispassword", CentersPreferred =  "Emergency Room", SkillsInterests =  "Health", Availability =  "MW", Address =  "100 You Drive", PhoneNumber =  "1234567890", Email =  "abigpredicament@aol.com", Education =  "Nursing", Licenses =  "Medical", EmergencyName =  "Seymour Problems", EmergencyPhone =  "8941209143", EmergencyEmail =  "problems@yahoo.com", EmergencyAddress =  "800 Palm Avenue", ValidLicense =  false, ValidSocial =  false, Approval  =  "Approved" },
new Volunteer { VolunteerID =  3, FirstName =  "Phil", LastName =  "Mycar", Username =  "Philly", Password =  "philadelphia294", CentersPreferred =  "Garage", SkillsInterests =  "Cars", Availability =  "RFS", Address =  "21 Flora Lane", PhoneNumber =  "9490828287", Email =  "carsarewesome@comcast.net", Education =  "Welding", Licenses =  "None", EmergencyName =  "Parker Now", EmergencyPhone =  "2309233482", EmergencyEmail =  "ineedmorecars@sbcglobal.net", EmergencyAddress =  "950 Honda Boulevard", ValidLicense =  true, ValidSocial =  false, Approval  =  "Disapproved" },
new Volunteer { VolunteerID =  4, FirstName =  "Sandy", LastName =  "Beaches", Username =  "theocean295", Password =  "loggerhead5213", CentersPreferred =  "Main Office/Beach", SkillsInterests =  "Science", Availability =  "MTF", Address =  "942 Beach Boulevard", PhoneNumber =  "9420000000", Email =  "iluvthebeach@gmail.com", Education =  "Ocean Science", Licenses =  "None", EmergencyName =  "Aneed Vacation", EmergencyPhone =  "9834934831", EmergencyEmail =  "whenisthenextvacation@hotmail.com", EmergencyAddress =  "1001 Party Place", ValidLicense =  false, ValidSocial =  false, Approval  =  "Pending Approval" },
new Volunteer { VolunteerID =  5, FirstName =  "Tara", LastName =  "Dactyl", Username =  "dinosaurus3", Password =  "password", CentersPreferred =  "Classroom", SkillsInterests =  "Science/Teaching", Availability =  "MTWRFS", Address =  "390 Ridgecrest Street", PhoneNumber =  "9870654321", Email =  "None", Education =  "Earth Science/Education", Licenses =  "Teaching", EmergencyName =  "Petra Fried", EmergencyPhone =  "1357024689", EmergencyEmail =  "imscared@aol.com", EmergencyAddress =  "1 Expensive Place", ValidLicense =  true, ValidSocial =  true, Approval  =  "Approved" }
 };
    }
}
